package com.example.weatherapp.Utils

object Constants {
    const val WEATHER_CONDITION_ID = "801"
    const val WEATHER_TYPE = "Clouds"
    const val WEATHER_CONDITION_DESCRIPTION = "few clouds"
    const val WEATHER_ICON_ID = "02d"
    const val TIME_DATA_FORECAST = "1614708000"
    const val TEMPERATURE = "30.84"
    const val THERMAL_SENSATION = "30.46"
    const val MINIMUM_TEMPERATURE = "30.84"
    const val MAXIMUM_TEMPERATURE = "33.2"
    const val ATMOSPHERIC_PRESSURE = "1005"
    const val ATMOSPHERIC_SEA_LEVEL = "1005"
    const val ATMOSPHERIC_GROUND_LEVEL = "992"
    const val HUMIDITY = "43"
    const val TEMP_KF = "-2.36"
    const val CLOUDINESS = "14"
    const val WIND_SPEED = "3.82"
    const val WIND_DIRECTION_DEGREES = "59"
    const val VISIBILITY = "10000"
    const val PROBABILITY_OF_PRECIPITATION = "0"
    const val PART_OF_DAY = "d"
    const val DATE_AND_TIME_THREE = "Fri, 05/03 00:00"
}
